apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000 # node group ID
        runAsUser: 1000  # node user ID
        runAsGroup: 1000 # node group ID
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["mkdir", "/metadata"]
        command: ["sh", "-c", "chown -R 1000:1000 /config /metadata"]
        volumeMounts:
          - name: audiobookshelf-data
            mountPath: /config
        securityContext:
          runAsUser: 0  # This specific container runs as root to fix things

      containers:
      - image: ghcr.io/advplyr/audiobookshelf:latest
        name: audiobookshelf
        env:
          # Define the environment variable
          - name: PORT # Notice that the case is different here
                                       # from the key name in the ConfigMap.
            valueFrom:
              configMapKeyRef:
                name: abs-config           # The ConfigMap this value comes from.
                key: PORT # The key to fetch.
        volumeMounts:
           - mountPath: /config
             name: audiobookshelf-data
      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc
