apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:latest
        name: audiobookshelf
        env:
          # Define the environment variable
          - name: PORT # Notice that the case is different here
                                       # from the key name in the ConfigMap.
            valueFrom:
              configMapKeyRef:
                name: abs-config           # The ConfigMap this value comes from.
                key: PORT # The key to fetch.
        volumeMounts:
           - mountPath: /etc/audiobookshelf/data
             name: audiobookshelf-data
  
      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc
