apiVersion: v1
data:
    password: ENC[AES256_GCM,data:lxTLZamo+mo=,iv:pJSgUlxswzmsev/gNDOSW4Z0Jf1y4Ccreq6HBKiUQoQ=,tag:8zc1765eL+vUBObOBtnpxg==,type:str]
    user: ENC[AES256_GCM,data:n0cAHnIFkjc=,iv:IREF+dzmteK1jjwoZPlmdv8SowSuCFKfJEkHVwo8fWk=,tag:bvjvXm187yQiprWppeDHfQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age19fnwysum8ve4wzj8nzwyjw3mz73tl0qplkdlyw8a48g425weqguq4g6nch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ0R4STEwT1d2MzNvSWhy
            Z1F3bkdGckdqUXVtVG45dnJTQnVRcjlaOFFRCitBOGFkdndHVkJDZ3ZWVitPcEQ0
            NTZYSzUzNC9uZEZ3ZGtkSTREcHRHMXMKLS0tIFh4cjZ0cGlZaXpNd1RCNFRlNVVG
            ZmU0S01PRUJ2aFJZYmk1NUFJSGlPNTAKyOCrpmK50ha/K0gdXsCXtlfXCSI2aTSd
            IzogPQOOKzM6NexjjbrWgDPOs5dIigHwjvpyj2a6kSQnQeAHLuVfCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T05:41:46Z"
    mac: ENC[AES256_GCM,data:c86hWH+ZIRrAz72e/HGPqkdKYFc15hX5wDV2dbHOsXwe4IfTt/B9m+yFwoeQvxOGFAOh3+Qhbk9hUh93rujjPOSOgJUC/PkwEXWWzc08qyG6LBSW71fMbtnsONVE7fThRAitjvRCj9XUoydILFy8++xuz/UBc81aOSA+P0iKHN4=,iv:dqb+X6YD/6WXarNengwTUApzkfsTmwVuSq6nCLJKwno=,tag:sMX/9MpF5aMkmsTDhGce5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
