apiVersion: kustomize.toolkit.fluxcd.io/v1 
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 1m
  sourceRef:
    kind: Gitrepository
    name: flux-system
  path: ./apps/staging
  prune: true
