apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:e/7K41Ml4M1ueWhVZWN4NmkDPY7oC7ZvouAVeotZFcKOu0r4rd3UWYoFUf8+ChPqtbakFmR6y9Z0H4jQp6v0DKuiRRe+o8Yj92Rbhisww3iZkiN55INNh8KZxWp4RTTfN9nw9NReQNAEBMP5tuET5CLAyKc3eFZu+0ZVeDEWMAIUpKh4B/MqPBApXaPsLReRTVFdHIh5H3NHschsDd3owFCwHEEoYkUImGoBVVJGbgARGrC69gDL9wl9wfGU/5AiNE04NYmIdBir+PPI5TUk7+nG59OVsKVcu4qswtVY9QGTElLOxl/2VftJtQA=,iv:8NQmkUavjyBByIBLLfWKe1MoFDUxDz+5U4zWBzBvi0g=,tag:MncuXSc98q5UsQ9ZPGj7YA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age19fnwysum8ve4wzj8nzwyjw3mz73tl0qplkdlyw8a48g425weqguq4g6nch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaytWRXJlZ2xnZkJVZm5V
            THBUMlBQL0pQNjd1VFBpd3RiUGNIa2FUSzI4CkNhRFM1SnhpdXdkVTZUZWlrMmRF
            L3dyS3BtZjA4S1Z4NEtxNEcrZENPaTAKLS0tIFlxMGlha3lackE2UE1TQjRqYUVw
            WDVtOHVvZm81MDZTRDRObGJ4YUxtckkK8+v1f/rGtKL721X8jesATgvfiZ3594xj
            t/3xSlzOnriBZ/9t5B19XswCsx4AkP5ssHQ8eLJgwpdkyXXdW262cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T06:16:26Z"
    mac: ENC[AES256_GCM,data:lk4jH4AGrzRdL74Ec0AfOyNPG3QR48AlQ2wCiSKSaRfYE4WNfVcGpVMejj16Jgp7YBqLdXFFYraRt8c1smaOuahgyg1O0h28ANABoQZcHOD++NksBetKVQzflUsRpUUxai8EFaNPHGu6TTEKW0j4XDUTzj/TWeh8zCgyNwpdKbU=,iv:TYoE6Xm9n7LhLUdCJjg0HCguzkrniSAJPTeNpmeE8HU=,tag:+P0LcjIolWPARMWR7GI+og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
