apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: pyproject-gitops-demo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: pyproject-gitops-demo
  filterTags:
#    pattern: '^sha-[a-f0-9]+'    # only match tags like sha-abc123
    pattern: '.*' 
    extract: '$0'
  policy:
    alphabetical:
      order: asc                  # pick the latest alphabetically
