apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pyproject-helloworld 
resources:
  - ../../base/pyproject-helloworld/
#  - cloudflare.yaml
#  - cloudflare-secret.yaml
#  - audiobooks-admin.yaml
