apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: linkding
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: linkding
  minReplicas: 1 # Idle state = 1 pod
  maxReplicas: 3 # Maximum pods allowed under heavy load
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Scale up when CPU exceeds 50% of 100m (50m)
